image:
  file: .gitpod/Dockerfile
  context: .

checkoutLocation: "joomlatools-server"

tasks:

  - name: Logs - Joomlatools Server
    init: |
      export APP_ENV=development
      export APP_PRELOAD=off
      export APP_CACHE=off
      export APP_DEBUG=on
    command: |
      clear
      sudo -E /init

  - name: Terminal - Joomlatools Server
    command: |
      clear
      echo ""
      echo "Commands you can try:"
      echo " * gp preview $(gp url 8080)/__info/php-info"
      echo " * mysql"
      echo " * joomla"

ports:
  - port: 8080
    onOpen: open-preview
    visibility: public
  - port: 8443
    onOpen: ignore
  - port: 8081
    onOpen: ignore
  - port: 8082
    onOpen: ignore
  - port: 9000
    onOpen: ignore
    visibility: private
  - port: 3306
    onOpen: ignore
    visibility: private

vscode:
  extensions:
    - cweijan.vscode-mysql-client2
    - bmewburn.vscode-intelephense-client
    - ecmel.vscode-html-css
